"""
    Spectre Information Center API

    Spectre Information Center API to access MySQL and Influx Databases.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spectre_api_client
from spectre_api_client.model.spy_all_of import SpyAllOf


class TestSpyAllOf(unittest.TestCase):
    """SpyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpyAllOf(self):
        """Test SpyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
