"""
    Spectre Information Center API

    Spectre Information Center API to access MySQL and Influx Databases.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import spectre_api_client
from spectre_api_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_command(self):
        """Test case for add_command

        Create new command  # noqa: E501
        """
        pass

    def test_add_data(self):
        """Test case for add_data

        Add new datapoints  # noqa: E501
        """
        pass

    def test_add_device(self):
        """Test case for add_device

        Create new device  # noqa: E501
        """
        pass

    def test_add_firmware(self):
        """Test case for add_firmware

        Add new firmware.  # noqa: E501
        """
        pass

    def test_add_mission(self):
        """Test case for add_mission

        Add new mission  # noqa: E501
        """
        pass

    def test_add_spy(self):
        """Test case for add_spy

        Create new spy  # noqa: E501
        """
        pass

    def test_add_textile(self):
        """Test case for add_textile

        Create new textile  # noqa: E501
        """
        pass

    def test_delete_command(self):
        """Test case for delete_command

        Delete command  # noqa: E501
        """
        pass

    def test_delete_device(self):
        """Test case for delete_device

        Delete device  # noqa: E501
        """
        pass

    def test_delete_firmware(self):
        """Test case for delete_firmware

        Delete firmware  # noqa: E501
        """
        pass

    def test_delete_mission(self):
        """Test case for delete_mission

        Delete mission  # noqa: E501
        """
        pass

    def test_delete_spy(self):
        """Test case for delete_spy

        Delete spy  # noqa: E501
        """
        pass

    def test_delete_textile(self):
        """Test case for delete_textile

        Delete textile  # noqa: E501
        """
        pass

    def test_get_command_by_id(self):
        """Test case for get_command_by_id

        Get command by id  # noqa: E501
        """
        pass

    def test_get_commands(self):
        """Test case for get_commands

        Get commands  # noqa: E501
        """
        pass

    def test_get_commands_from_mission(self):
        """Test case for get_commands_from_mission

        Get commands of a mission  # noqa: E501
        """
        pass

    def test_get_dashboard_data_from_mission(self):
        """Test case for get_dashboard_data_from_mission

        Get dashboard data of a mission  # noqa: E501
        """
        pass

    def test_get_dashboard_from_mission(self):
        """Test case for get_dashboard_from_mission

        Get dashboard of a mission  # noqa: E501
        """
        pass

    def test_get_data(self):
        """Test case for get_data

        Get data from influxDB  # noqa: E501
        """
        pass

    def test_get_dataseries_by_id(self):
        """Test case for get_dataseries_by_id

        Get data from influxDB  # noqa: E501
        """
        pass

    def test_get_dataseries_from_mission(self):
        """Test case for get_dataseries_from_mission

        Get dataseries of a mission  # noqa: E501
        """
        pass

    def test_get_device_by_id(self):
        """Test case for get_device_by_id

        Get devices  # noqa: E501
        """
        pass

    def test_get_devices(self):
        """Test case for get_devices

        Get devices  # noqa: E501
        """
        pass

    def test_get_firmware_by_id(self):
        """Test case for get_firmware_by_id

        Get information about a specific firmware  # noqa: E501
        """
        pass

    def test_get_firmware_from_mission(self):
        """Test case for get_firmware_from_mission

        Get firmware of a mission  # noqa: E501
        """
        pass

    def test_get_firmware_list(self):
        """Test case for get_firmware_list

        Get available firmware versions  # noqa: E501
        """
        pass

    def test_get_missions(self):
        """Test case for get_missions

        Get missions  # noqa: E501
        """
        pass

    def test_get_missions_by_id(self):
        """Test case for get_missions_by_id

        Get missions with a specific ID  # noqa: E501
        """
        pass

    def test_get_next_pending_mission(self):
        """Test case for get_next_pending_mission

        Get next pending mission for a spy  # noqa: E501
        """
        pass

    def test_get_spies(self):
        """Test case for get_spies

        Get all spies  # noqa: E501
        """
        pass

    def test_get_spy(self):
        """Test case for get_spy

        Get spy  # noqa: E501
        """
        pass

    def test_get_spy_by_id(self):
        """Test case for get_spy_by_id

        Get a specific spy  # noqa: E501
        """
        pass

    def test_get_spy_from_mission(self):
        """Test case for get_spy_from_mission

        Get spy of a mission  # noqa: E501
        """
        pass

    def test_get_textile_by_id(self):
        """Test case for get_textile_by_id

        Get a specific textile  # noqa: E501
        """
        pass

    def test_get_textile_from_mission(self):
        """Test case for get_textile_from_mission

        Get textile of a mission  # noqa: E501
        """
        pass

    def test_get_textiles(self):
        """Test case for get_textiles

        Get all textiles  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        Returns the API version  # noqa: E501
        """
        pass

    def test_update_command(self):
        """Test case for update_command

        Update command  # noqa: E501
        """
        pass

    def test_update_device(self):
        """Test case for update_device

        Update device  # noqa: E501
        """
        pass

    def test_update_firmware(self):
        """Test case for update_firmware

        Update firmware  # noqa: E501
        """
        pass

    def test_update_mission(self):
        """Test case for update_mission

        Update mission  # noqa: E501
        """
        pass

    def test_update_spy(self):
        """Test case for update_spy

        Update spy  # noqa: E501
        """
        pass

    def test_update_textile(self):
        """Test case for update_textile

        Update textile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
