"""
    Spectre Information Center API

    Spectre Information Center API to access MySQL and Influx Databases.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spectre_api_client
from spectre_api_client.model.spy_all_of import SpyAllOf
from spectre_api_client.model.spy_status import SpyStatus
globals()['SpyAllOf'] = SpyAllOf
globals()['SpyStatus'] = SpyStatus
from spectre_api_client.model.spy import Spy


class TestSpy(unittest.TestCase):
    """Spy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpy(self):
        """Test Spy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Spy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
