"""
    Spectre Information Center API

    Spectre Information Center API to access MySQL and Influx Databases.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spectre_api_client
from spectre_api_client.model.id_obj import IdObj


class TestIdObj(unittest.TestCase):
    """IdObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdObj(self):
        """Test IdObj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdObj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
